drop table ciudad CASCADE CONSTRAINTS;
drop table region CASCADE CONSTRAINTS;
drop table cliente CASCADE CONSTRAINTS;
drop table cobertura CASCADE CONSTRAINTS;
drop table marca CASCADE CONSTRAINTS;
drop table modelo CASCADE CONSTRAINTS;
drop table seguro CASCADE CONSTRAINTS;
drop table siniestro CASCADE CONSTRAINTS;
drop table vehiculo CASCADE CONSTRAINTS;
drop table taller CASCADE CONSTRAINTS;
drop table movimiento CASCADE CONSTRAINTS;
drop table EMPLEADO CASCADE CONSTRAINTS;
drop table CARGO CASCADE CONSTRAINTS;
drop table GRUA CASCADE CONSTRAINTS;

CREATE TABLE CIUDAD
  (
    id_ciudad        NUMBER (3) NOT NULL ,
    nombre           VARCHAR2 (40) NOT NULL ,
    REGION_id_region NUMBER (2) NOT NULL
  ) ;
ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_PK PRIMARY KEY ( id_ciudad ) ;

CREATE TABLE CARGO
  (
    id_Cargo NUMBER(3) NOT NULL,
    nombre VARCHAR2(50) NOT NULL
  ) ;
ALTER TABLE CARGO ADD CONSTRAINT CARGO_PK PRIMARY KEY ( id_Cargo ) ;

CREATE TABLE EMPLEADO
  (
    id_empleado    VARCHAR2 (10) NOT NULL ,
    rut              VARCHAR2 (10) NOT NULL ,
    pass             VARCHAR2 (200) NOT NULL ,
    nombres          VARCHAR2 (50) NOT NULL ,
    apellidos        VARCHAR2 (50) NOT NULL ,
    correo           VARCHAR2 (50) NOT NULL ,
    fono             VARCHAR2 (20) NOT NULL ,
    fecha_nacimiento VARCHAR2 (50) NOT NULL ,
    direccion        VARCHAR2 (100) NOT NULL ,
    CIUDAD_id_ciudad        NUMBER (3) NOT NULL,
    CARGO_id_cargo            NUMBER(3) NOT NULL
  ) ;
CREATE UNIQUE INDEX EMPLEADO__IDX ON EMPLEADO
  (
    rut ASC
  )
  ;
ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_PK PRIMARY KEY ( id_empleado ) ;

CREATE TABLE CLIENTE
  (
    id_cliente           VARCHAR2 (10) NOT NULL ,
    rut                  VARCHAR2 (10) NOT NULL ,
    pass                 VARCHAR2 (200) NOT NULL ,
    nombres              VARCHAR2 (50) NOT NULL ,
    apellidos            VARCHAR2 (50) NOT NULL ,
    correo               VARCHAR2 (50) NOT NULL ,
    fono                 VARCHAR2 (20) NOT NULL ,
    fecha_nacimiento     DATE NOT NULL ,
    direccion            VARCHAR2 (100) NOT NULL ,
    VEHICULO_id_vehiculo VARCHAR2 (10) NOT NULL ,
    SEGURO_id_seguro     VARCHAR2 (10) NOT NULL ,
    CIUDAD_id_ciudad            NUMBER (3) NOT NULL
  ) ;
CREATE UNIQUE INDEX CLIENTE__IDX ON CLIENTE
  (
    rut ASC
  )
  ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( id_cliente ) ;


CREATE TABLE COBERTURA
  (
    id_cobertura  VARCHAR2 (10) NOT NULL ,
    perdida_total CHAR (1) NOT NULL ,
    dano_terceros CHAR (1) NOT NULL
  ) ;
ALTER TABLE COBERTURA ADD CONSTRAINT COBERTURA_PK PRIMARY KEY ( id_cobertura ) ;

CREATE TABLE MARCA
  (
    id_marca VARCHAR2 (10) NOT NULL ,
    nombre   VARCHAR2 (40) NOT NULL
  ) ;
ALTER TABLE MARCA ADD CONSTRAINT MARCA_PK PRIMARY KEY ( id_marca ) ;


CREATE TABLE MODELO
  (
    id_modelo      VARCHAR2 (10) NOT NULL ,
    nombre         VARCHAR2 (40) NOT NULL ,
    MARCA_id_marca VARCHAR2 (10) NOT NULL
  ) ;
ALTER TABLE MODELO ADD CONSTRAINT MODELO_PK PRIMARY KEY ( id_modelo ) ;


CREATE TABLE REGION
  (
    id_region NUMBER (2) NOT NULL ,
    nombre    VARCHAR2 (40) NOT NULL
  ) ;
ALTER TABLE REGION ADD CONSTRAINT REGION_PK PRIMARY KEY ( id_region ) ;


CREATE TABLE SEGURO
  (
    id_seguro              VARCHAR2 (10) NOT NULL ,
    valor                  NUMBER (7) NOT NULL ,
    activo                 CHAR (1) NOT NULL,  
    COBERTURA_id_cobertura VARCHAR2 (10) NOT NULL
  ) ;
CREATE UNIQUE INDEX SEGURO__IDX ON SEGURO
  (
    COBERTURA_id_cobertura ASC
  )
  ;
ALTER TABLE SEGURO ADD CONSTRAINT SEGURO_PK PRIMARY KEY ( id_seguro ) ;


CREATE TABLE SINIESTRO
  (
    id_siniestro             VARCHAR2 (10) NOT NULL ,
    fecha                    DATE NOT NULL ,
    fecha_termino            DATE ,
    estado                   VARCHAR2 (20) NOT NULL ,
    deducible_uf             NUMBER (3) NOT NULL ,
    coste_reparacion         NUMBER (10) ,
    CLIENTE_id_cliente       VARCHAR2 (10) NOT NULL ,
    EMPLEADO_id_empleado	     VARCHAR2 (10) NOT NULL
  ) ;
ALTER TABLE SINIESTRO ADD CONSTRAINT SINIESTRO_PK PRIMARY KEY ( id_siniestro ) ;


CREATE TABLE VEHICULO
  (
    id_vehiculo        VARCHAR2 (10) NOT NULL ,
    patente            VARCHAR2 (10) NOT NULL ,
    ano                NUMBER (4) NOT NULL ,
    valor_fiscal       NUMBER (9) NOT NULL ,
    MODELO_id_modelo          VARCHAR2 (10) NOT NULL
  ) ;
ALTER TABLE VEHICULO ADD CONSTRAINT VEHICULO_PK PRIMARY KEY ( id_vehiculo ) ;



CREATE TABLE MOVIMIENTO
  (
    id_movimiento	VARCHAR2(10) NOT NULL,
    fecha		DATE NOT NULL,
    descripcion		VARCHAR2(200) NOT NULL,
    SINIESTRO_id_siniestro	VARCHAR2(10) NOT NULL
  ) ;
ALTER TABLE MOVIMIENTO ADD CONSTRAINT MOVIMIENTO_PK PRIMARY KEY ( id_movimiento ) ;

CREATE TABLE TALLER
  (
    id_taller	VARCHAR2(10) NOT NULL,
    nombre	VARCHAR2(100) NOT NULL,
    fono		VARCHAR2(20) NOT NULL,
    direccion	VARCHAR2(100) NOT NULL,
    CIUDAD_id_ciudad	NUMBER (3) NOT NULL,
    EMPLEADO_id_empleado	VARCHAR2(10) NOT NULL
  ) ;
ALTER TABLE TALLER ADD CONSTRAINT TALLER_PK PRIMARY KEY ( id_taller ) ;
CREATE UNIQUE INDEX TALLER__IDX ON TALLER
  (
    EMPLEADO_id_empleado ASC
  )
  ;

CREATE TABLE GRUA
  (
    id_grua NUMBER(3) NOT NULL,
    rut     VARCHAR2(10) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    fono VARCHAR2(20) NOT NULL,
    direccion VARCHAR2(100) NOT NULL,
    CIUDAD_id_ciudad NUMBER (3) NOT NULL
  ) ;
ALTER TABLE GRUA ADD CONSTRAINT GRUA_PK PRIMARY KEY ( id_grua ) ;
CREATE UNIQUE INDEX GRUA__IDX ON GRUA
  (
    rut ASC
  )
  ;


ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_CARGO_FK FOREIGN KEY (CARGO_id_cargo) REFERENCES CARGO (id_cargo) ;

ALTER TABLE TALLER ADD CONSTRAINT TALLER_EMPLEADO_FK FOREIGN KEY (EMPLEADO_id_empleado) REFERENCES EMPLEADO (id_empleado) ;

ALTER TABLE TALLER ADD CONSTRAINT TALLER_CIUDAD_FK FOREIGN KEY (CIUDAD_id_ciudad) REFERENCES CIUDAD (id_ciudad) ;

ALTER TABLE GRUA ADD CONSTRAINT GRUA_CIUDAD_FK FOREIGN KEY (CIUDAD_id_ciudad) REFERENCES CIUDAD (id_ciudad) ;

ALTER TABLE MOVIMIENTO ADD CONSTRAINT MOVIMIENTO_SINIESTRO_FK FOREIGN KEY ( SINIESTRO_id_siniestro ) REFERENCES SINIESTRO ( id_siniestro ) ;

ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_REGION_FK FOREIGN KEY ( REGION_id_region ) REFERENCES REGION ( id_region ) ;

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_SEGURO_FK FOREIGN KEY ( SEGURO_id_seguro ) REFERENCES SEGURO ( id_seguro ) ;

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_VEHICULO_FK FOREIGN KEY ( VEHICULO_id_vehiculo ) REFERENCES VEHICULO ( id_vehiculo ) ;

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_CIUDAD_FK FOREIGN KEY (CIUDAD_id_ciudad) REFERENCES CIUDAD (id_ciudad) ;

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_CIUDAD_FK FOREIGN KEY (CIUDAD_id_ciudad) REFERENCES CIUDAD (id_ciudad) ;

ALTER TABLE VEHICULO ADD CONSTRAINT VEHICULO_MODELO_FK FOREIGN KEY (MODELO_id_modelo) REFERENCES MODELO (id_modelo) ;

ALTER TABLE MODELO ADD CONSTRAINT MODELO_MARCA_FK FOREIGN KEY ( MARCA_id_marca ) REFERENCES MARCA ( id_marca ) ;

ALTER TABLE SEGURO ADD CONSTRAINT SEGURO_COBERTURA_FK FOREIGN KEY ( COBERTURA_id_cobertura ) REFERENCES COBERTURA ( id_cobertura ) ;

ALTER TABLE SINIESTRO ADD CONSTRAINT SINIESTRO_CLIENTE_FK FOREIGN KEY ( CLIENTE_id_cliente ) REFERENCES CLIENTE ( id_cliente ) ;

ALTER TABLE SINIESTRO ADD CONSTRAINT SINIESTRO_EMPLEADO_FK FOREIGN KEY ( EMPLEADO_id_empleado ) REFERENCES EMPLEADO ( 
id_empleado ) ;