/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.Empleados;

import Datos.FafricaConexion;
import Entidades.Siniestro;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import java.util.List;
import java.util.Locale;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author DarKMeYeR
 */
public class Reportes extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("SeguroEscritorioPU");
    EntityManager em = emf.createEntityManager();
    Connection cn = null;
    public Reportes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbSinVsCli = new javax.swing.JComboBox<>();
        btnMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jpChart = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        cbSinVsCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siniestros vs Clientes", "Vehiculos vs Siniestros" }));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria:");

        jpChart.setBackground(new java.awt.Color(204, 204, 204));
        jpChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSinVsCli, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSinVsCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jpChart, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTES BI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
    try {
        if(cn == null || cn.isClosed())
            cn = new FafricaConexion().Conectar();
        switch(cbSinVsCli.getSelectedItem().toString())
        {            
            case "Siniestros vs Clientes": clienteVsSieniestro(); break;
            case "Vehiculos vs Siniestros": VehiculoVsSieniestro(); break;
        }
        cn.close();
    }catch(Exception e){}
    }//GEN-LAST:event_btnMostrarActionPerformed

    public void clienteVsSieniestro()
    {
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        barchartdata.setValue(cantidadSiniestros(), "Cantidad", "Siniestros");
        barchartdata.setValue(cantidadClientes(), "Cantidad", "Clientes");
        JFreeChart barchart = ChartFactory.createBarChart(cbSinVsCli.getSelectedItem().toString(), "", "Cantidad", barchartdata,PlotOrientation.VERTICAL,false,true,false);        
        CategoryPlot barchrt=barchart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.BLUE);
        
        final GradientPaint gp0 = new GradientPaint(
                    0.0f, 0.0f, new Color(31, 95, 193), 
                    0.0f, 0.0f, new Color(47, 191, 236)
                );
        
        ((BarRenderer)barchrt.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer)barchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, gp0);
        ChartPanel barPanel = new ChartPanel(barchart);
        jpChart.removeAll();
        jpChart.add(barPanel, BorderLayout.CENTER);
        jpChart.validate();
    }
    
    public void VehiculoVsSieniestro()
    {
        DefaultPieDataset piechartdata = new DefaultPieDataset();
        piechartdata.setValue("Vehiculos",cantidadVehiculos());
        piechartdata.setValue("Siniestros",cantidadSiniestros());
        JFreeChart chart = ChartFactory.createPieChart(cbSinVsCli.getSelectedItem().toString(), piechartdata, true, true, true);
        PiePlot chrt=(PiePlot)chart.getPlot();
        ChartPanel piePanel = new ChartPanel(chart);
        jpChart.removeAll();
        jpChart.add(piePanel, BorderLayout.CENTER);
        jpChart.validate();
    }
    
    public int cantidadVehiculos()
    {
        int cantidad = 0;
        try {
            CallableStatement cs = cn.prepareCall("{call ? := F_CANTIDAD_VEHICULOS}");
            cs.registerOutParameter(1, Types.NUMERIC);
            cs.executeUpdate();
            cantidad = cs.getInt(1);  
            cs.close();
            return cantidad;
        } catch (Exception e) {
            return 0;
        }
    }
    
    public int cantidadSiniestros()
    {
        int cantidad = 0;
        try {
            CallableStatement cs = cn.prepareCall("{call ? := F_CANTIDAD_SINIESTROS}");
            cs.registerOutParameter(1, Types.NUMERIC);
            cs.executeUpdate();
            cantidad = cs.getInt(1);
            cs.close();
            return cantidad;
        } catch (Exception e) {
            return 0;
        }
    }
    
    public int cantidadClientes()
    {
        int cantidad = 0;
        try {
            CallableStatement cs = cn.prepareCall("{call ? := F_CANTIDAD_CLIENTES}");
            cs.registerOutParameter(1, Types.NUMERIC);
            cs.executeUpdate();
            cantidad = cs.getInt(1);
            cs.close();
            return cantidad;
        } catch (Exception e) {
            return 0;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cbSinVsCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpChart;
    // End of variables declaration//GEN-END:variables
}
