/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author DarKMeYeR
 */
public class Menu extends javax.swing.JFrame {

    
    
    public Menu(String nombre) {
        initComponents();
        bienvenida(nombre);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemEmpleado = new javax.swing.JMenuItem();
        itemRegionCiudad = new javax.swing.JMenuItem();
        itemTaller = new javax.swing.JMenuItem();
        itemGrua = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Administracion");

        lblBienvenida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("Menu Mantenedores");

        itemEmpleado.setText("Empleado");
        itemEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemEmpleadoMouseClicked(evt);
            }
        });
        itemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(itemEmpleado);

        itemRegionCiudad.setText("Region/Ciudad");
        itemRegionCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegionCiudadActionPerformed(evt);
            }
        });
        jMenu1.add(itemRegionCiudad);

        itemTaller.setText("Taller");
        itemTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTallerActionPerformed(evt);
            }
        });
        jMenu1.add(itemTaller);

        itemGrua.setText("Grua");
        itemGrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGruaActionPerformed(evt);
            }
        });
        jMenu1.add(itemGrua);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadoActionPerformed
        new EmpleadoMantenedor().setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_itemEmpleadoActionPerformed

    private void itemEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEmpleadoMouseClicked

    private void itemRegionCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegionCiudadActionPerformed
        new RegionCiudadMantenedor().setVisible(true);
    }//GEN-LAST:event_itemRegionCiudadActionPerformed

    private void itemTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTallerActionPerformed
        new TallerMantenedor().setVisible(true);
    }//GEN-LAST:event_itemTallerActionPerformed

    private void itemGruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGruaActionPerformed
        new GruaMantenedor().setVisible(true);
    }//GEN-LAST:event_itemGruaActionPerformed

    private void bienvenida(String nombre) {
        lblBienvenida.setText("Bienvenid@ "+nombre);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemEmpleado;
    private javax.swing.JMenuItem itemGrua;
    private javax.swing.JMenuItem itemRegionCiudad;
    private javax.swing.JMenuItem itemTaller;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables

    
}
